workflow:
  start-at: registration
  stop-at: downstream
  background: true
  segmentation-channel: 1
  segmentation-recyze: true
  segmentation: cellpose
options:
  cellpose: --pretrained_model nuclei --chan 0 --diameter 50 --no_npy
  ashlar: --flip-y


